package ai.hev.app.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.sqlite.SQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

@Database(entities = [HistoryEntity::class], version = 3, exportSchema = true)
@ConstructedBy(HevDatabaseConstructor::class)
abstract class HevDatabase : RoomDatabase() {
    abstract fun historyDao(): HistoryDao

    companion object {
        const val NAME = "hev.db"
    }
}

/** Generated by Room for each platform. */
@Suppress("KotlinNoActualForExpect")
expect object HevDatabaseConstructor : RoomDatabaseConstructor<HevDatabase> {
    override fun initialize(): HevDatabase
}

/** Completes a platform builder: the given driver, every migration, and queries off the caller's thread. */
internal fun RoomDatabase.Builder<HevDatabase>.build(driver: SQLiteDriver): HevDatabase =
    setDriver(driver)
        .addMigrations(*HevMigrations.ALL)
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()
